### ISSUE TITLE
Crash on "reset zoom"

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/uNav_PID_Tuner#10]
When running uNav PID Tuner I have a crash when I click on "reset zoom" if I have uncheck the enable 0.
Before I receive same error when check "enable 0" and click on "Start motor".

```
ASSERT: "!isEmpty()" in file /usr/include/qt5/QtCore/qvector.h, line 191
The program has unexpectedly finished.
```

I'm using

```
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
on
Linux ubuntu 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Myzhar** [comment]
Solved with commit 76a71df951ea0109a17dc6b9073d3ad927e00e8c
