### ISSUE TITLE
Software Stability

### ISSUE THREAD

**Issue by gbr1** [officinerobotiche/uNav_PID_Tuner#15]
Software crash when you disconnect then reconnect.  Sometimes crash during connection on starting.

**Comment by Myzhar** [comment]
I'm aware of this problem.
I'm going to figure out why it's happening, it's difficult, but I have a few ideas

**Comment by rbonghi** [comment]
Solved https://github.com/officinerobotiche/orblibcpp/commit/c51180cb90db4d1edd026b1e75bc42a60b1bf85e :+1:
