### ISSUE TITLE
Add code to send commands

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/uNav_PID_Tuner#2]
@rbonghi please find "TODO: x Raffaello" in [mainwindow.cpp](https://github.com/officinerobotiche/uNav_PID_Tuner/blob/master/src/mainwindow.cpp) and add the correct code to perform the operation as described.

There are in total 3 code snippets to be added

**Comment by rbonghi** [comment]
Solve bc6bd9c1c14b404b37cca4844ac4104ee37a1169
