### ISSUE TITLE
Error in Kp, Ki and Kd sending

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/uNav_PID_Tuner#9]
With motor runing, if I update value of Ki, Kp or Pd and press to "Send" stop motor.Get return 0,00 value for each parameter.
If I try Get before Send displayed value remain value of connection ( 0,6 0,5 0,0 )

**Comment by Myzhar** [comment]
Note: try to set k params in synchronous modw

**Comment by Myzhar** [comment]
@myzhar Add the control about the validity of the data inserted in the forms. 

@katodo the application is in English language, the decimal are represented using dots, not commas ;-)

**Comment by katodo** [comment]
ok, but in my gui data input area display value with comma.  In my test I
do send without change value.

Mauro Soligo by Sony Xperia Z

**Comment by katodo** [comment]
I've tryed now, in GUI I can't change comma with dot by hand.

**Comment by Myzhar** [comment]
This is really bad... I hate this kind of issue. I hate "locale" at all!!!
